from rest_framework import renderers, schemas
from openapi_codec import OpenAPICodec
from django.conf import settings

generator = schemas.SchemaGenerator(title=settings.SCHEMA_NAME)
class SwaggerJSRenderer(renderers.BaseRenderer):
    media_type = 'application/openapi+json'
    format = 'swagger'

    def render(self, data, media_type=None, renderer_context=None):
        codec = OpenAPICodec()
        return "//AUTO_GENERATED\n//Swagger schema generated by Django App\nexport default " + codec.dump(data) + '\n'

def export_schema():
	with open(settings.SCHEMA_DESTINATION, 'w') as f:
		f.write(SwaggerJSRenderer().render(generator.get_schema()))
